### ISSUE TITLE
New User not getting added 

### ISSUE THREAD

**Issue by sanjib-dev** [ADmad/CakePHP-HybridAuth#71]
I keep getting this error:
You must attach a listener for "HybridAuth.newUser" event which saves new user record and returns an user entity.

I use CakePhp 3.2
this is my url
http://www.elearnmarkets.in/elm/login

**Comment by ADmad** [comment]
So do what error message tells you to do. The README explain how to add listener for that event.

**Comment by sanjib-dev** [comment]
did exactly whats in the README expalins...but still the error persists...even tried to add global listeners..it seems the event is getting catch in the code..
I do have some other global listeners attached in the code but this seems not working

**Comment by dereuromark** [comment]
I ran into the issue in some edge cases.
The profile is stored, the user is logged in partially already but then it stops with this exception

> [RuntimeException]
You must attach a listener for "HybridAuth.newUser" event
which saves new user record and returns an user entity.

Stacktrace:
```
#0 /app/vendor/admad/cakephp-hybridauth/src/Auth/HybridAuthAuthenticate.php(319): ADmad\HybridAuth\Auth\HybridAuthAuthenticate->_newUser(Object(ADmad\HybridAuth\Model\Entity\SocialProfile))
#1 /app/vendor/admad/cakephp-hybridauth/src/Auth/HybridAuthAuthenticate.php(184): ADmad\HybridAuth\Auth\HybridAuthAuthenticate->_getUser(Object(Hybrid_Provider_Adapter))
#2 /app/vendor/admad/cakephp-hybridauth/src/Auth/HybridAuthAuthenticate.php(199): ADmad\HybridAuth\Auth\HybridAuthAuthenticate->getUser(Object(Cake\Http\ServerRequest))
#3 /app/vendor/cakephp/cakephp/src/Controller/Component/AuthComponent.php(824): ADmad\HybridAuth\Auth\HybridAuthAuthenticate->authenticate(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#4 /app/vendor/admad/cakephp-hybridauth/src/Controller/HybridAuthController.php(49): Cake\Controller\Component\AuthComponent->identify()
#5 /app/vendor/cakephp/cakephp/src/Controller/Controller.php(610): ADmad\HybridAuth\Controller\HybridAuthController->authenticated()
#6 /app/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(120): Cake\Controller\Controller->invokeAction()
#7 /app/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(94): Cake\Http\ActionDispatcher->_invoke(Object(ADmad\HybridAuth\Controller\HybridAuthController))
#8 /app/vendor/cakephp/cakephp/src/Http/BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 /app/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 /app/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(162): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 /app/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
```

Not sure how to consistently reproduce.
Also not sure if it is worth it, I will try to migrate to social auth soon.
